#cloud-config
package_update: true
package_upgrade: true

packages:
 - curl
 - python3-pip
 - python3-venv
 - ca-certificates
 - gnupg

runcmd:
 # install gcloud
 - mkdir -p /usr/local/google-cloud-sdk
 - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz  
 - tar -xzf /tmp/google-cloud-sdk.tar.gz -C /usr/local
 - echo 'export PATH=$PATH:/usr/local/google-cloud-sdk/bin' > /etc/profile.d/gcloud-path.sh
 - /usr/local/google-cloud-sdk/install.sh --quiet --install-python false --usage-reporting false --rc-path=/root/.bashrc --command-completion true --path-update true
 - rm /tmp/google-cloud-sdk.tar.gz
 - chmod +x /etc/profile.d/gcloud-path.sh
 
 # install docker
 - install -m 0755 -d /etc/apt/keyrings
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
 - chmod a+r /etc/apt/keyrings/docker.gpg
 - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
 - apt-get update
 - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
 - systemctl enable docker
 - systemctl start docker
 - usermod -aG docker ubuntu

